name: 'Write a version to gradle.properties'
description: 'Git operation to commit the bump of a new version'
inputs:
  field-name:
    description: 'The name of the field to read'
    required: false
    default: 'version'
  field-value:
    description: 'The version set after this build'
    required: true
    default: 'X.X.XX'
runs:
  using: 'composite'
  steps:
    - name: 'Write version'
      id: write-version
      shell: bash
      run: |
        fieldname=${{ inputs.field-name }}
        newversion=${{ inputs.field-value }}
        sed -i "s/^${fieldname}=.*/${fieldname}=${newversion}/" gradle.properties
        git add gradle.properties
        git commit -m "[ci] update ${fieldname} in gradle.properties" || echo "No changes to commit"
        git push origin
